### ISSUE TITLE
Bowl GUI has a partially invisible button

### ISSUE THREAD

**Issue by RisingInIris2017** [Snownee/Cuisine2#12]
#### MOD版本 - Mod version:

Cuisine 2 Version: https://github.com/Snownee/Cuisine2/actions/runs/45764164
Kiwi Version: Kiwi-1.15.2-2.7.0
MixinBootstrap Version: MixinBootstrap-1.0.2
#### Forge版本 - Forge version:

31.1.1

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

Singleplayer

#### 完整的MOD列表 - Installed mods:

![](在此处填入你的截图链接，没有截图请删除此行 Paste your screenshot link here, or delete this line)
Cuisine 2 Version: https://github.com/Snownee/Cuisine2/actions/runs/45764164
Kiwi Version: Kiwi-1.15.2-2.7.0
MixinBootstrap Version: MixinBootstrap-1.0.2
All mods are listed here.

## 崩溃报告的链接 - Link to full crash log

Game does not crash.

#### 产生Bug的步骤 - How to reproduce:

1. Place a Bowl onto ground.
2. Open its GUI.
3. See such a weird button.

#### 反映Bug的图片 - Pictures:

![](https://i.imgur.com/avfIRim.gif)

**Comment by Snownee** [comment]
WIP
